[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Обработка статических файлов
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200